### ISSUE TITLE
The racer process has stopped

### ISSUE THREAD

**Issue by danslapman** [saviorisdead/RustyCode#19]
Hello! I'm constantly receiving message `The racer process has stopped` every time I open *.rs file. Autocompletion is not working...

There is also an error in console:
```
TypeError: Cannot read property 'statusBarEntry' of null: TypeError: Cannot read property 'statusBarEntry' of null
    at StatusBarService.toggleStatus (C:\Users\Daniil\.vscode\extensions\saviorisdead.RustyCode\out\src\services\statusBarService.js:19:18)
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:7:17111)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:7:18469)
    at e._acceptActiveEditorAndVisibleEditors (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:17:10238)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:14:2604)
    at a (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:11:16863)
    at Object.p.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:11:17427)
    at process.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:19:9111)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
```

**Comment by saviorisdead** [comment]
Hi there, thanks for reporting.
Could you provide some additional information, like is your RustyCode settings? Are you sure you have correct value in `racer.Path`?
Also, please, try running racer directly from console, like this `racer complete {linenum} {charnum}`.

**Comment by danslapman** [comment]
Here are my settings:
```
"rust.rustLangSrcPath": "C:/Users/dansl/Documents/Projects/rust/src",
"rust.racerPath": "C:/Users/dansl/Documents/Projects/racer/target/release"
```
Checked running racer in console, completion suggestion works well.

**Comment by saviorisdead** [comment]
This
`"rust.racerPath": "C:/Users/dansl/Documents/Projects/racer/target/release"`
Should be this
`"rust.racerPath": "C:/Users/dansl/Documents/Projects/racer/target/release/racer"`
racerPath is path to executable of racer

**Comment by danslapman** [comment]
Changed my settings. Now I receive `The racer process has stopped` on hitting `Ctrl+Shift+Space`

**Comment by danslapman** [comment]
Hmm... It seems that I'm facing this bug: https://github.com/phildawes/racer/issues/433
I tried to complete using :) Method completion now works well, thanks!

**Comment by saviorisdead** [comment]
No problem :)

**Comment by danslapman** [comment]
Just to inform, the real problem was https://github.com/phildawes/racer/issues/434
