### ISSUE TITLE
Extension crashes on new error format

### ISSUE THREAD

**Issue by RReverser** [saviorisdead/RustyCode#210]
From time to time extension apparently fails to parse some Rust errors (can't provide specific reproducible example yet unfortunately, but suspect it's related to human-readable borrow checker errors which are more complex than regular ones) and completely stops working until VSCode reload/restart.

Here is stack trace:

```
shell.ts:441Cannot read property '1' of null: TypeError: Cannot read property '1' of null
    at Function.CommandService.parseNewHumanReadable (C:\Users\Ingvar\.vscode\extensions\saviorisdead.RustyCode-0.19.1\out\src\services\commandService.js:331:53)
    at Function.CommandService.parseDiagnostics (C:\Users\Ingvar\.vscode\extensions\saviorisdead.RustyCode-0.19.1\out\src\services\commandService.js:230:18)
    at C:\Users\Ingvar\.vscode\extensions\saviorisdead.RustyCode-0.19.1\out\src\services\commandService.js:408:27
    at process._tickCallback (internal/process/next_tick.js:103:7)e.onUnexpectedError @ shell.ts:441
```

**Comment by daiheitan** [comment]
Seems that RustyCode is broken with latest nightly

**Comment by vvuk** [comment]
Yep, looks like some protection would probably be worthwhile here, especially if it horks VSCode entirely

**Comment by Jascha-N** [comment]
Happening consistently with the new multi-line span error messages. Makes the entire extension unresponsive.

**Comment by CryZe** [comment]
Oh yeah, this needs a fix really soon, as the whole extension is broken with the latest Rust nightlies. Pinging @KalitaAlexey

**Comment by vvuk** [comment]
Works for me in https://github.com/saviorisdead/RustyCode/pull/229 so perhaps one commit was missed.  I'll take a look and submit PRs when I get a chance, but better might be to just cherry pick everything from there.
