### ISSUE TITLE
The racer process has stopped

### ISSUE THREAD

**Issue by zonyitoo** [saviorisdead/RustyCode#33]
Rustc version

```
rustc 1.6.0-nightly (9303055f3 2015-11-19)
```

I have never succeeded to start the racer process, which crashed every time when I open a `.rs` file with exactly the same error:

```
TypeError: Cannot read property 'statusBarEntry' of null: TypeError: Cannot read property 'statusBarEntry' of null
    at StatusBarService.toggleStatus (/Users/zonyitoo/.vscode/extensions/saviorisdead.RustyCode/out/src/services/statusBarService.js:19:18)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:17111)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:18469)
    at e._acceptActiveEditorAndVisibleEditors (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:17:10238)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:14:2604)
    at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:11:16863)
    at Object.p.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:11:17427)
    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:19:9111)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
```

VSCode version: `0.10.2 (7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066)`

Racer runs fine in terminal, also works fine in Atom and Sublime Text.

**Comment by saviorisdead** [comment]
I think it's related to this -> #19 
And please, make sure you've got correct paths for racer and rust-lang src/ folder in settings.

**Comment by Draivin** [comment]
The error `statusBarEntry` is not related to racer in any way, it was a forgotten bind when passing the Status Bar Service to vscode.

As of latest version, you should be able to click 'view errors' when racer crashes, so you can see what caused the crash.

**Comment by Draivin** [comment]
It may also be related to https://github.com/saviorisdead/RustyCode/issues/38, caused by an outdated racer that does not have a `daemon` command.

**Comment by saviorisdead** [comment]
Is there any additional information about this issue? Is it resolved?

**Comment by zonyitoo** [comment]
Unfortunately no. I am quite busy these days, I will try the version on master later.

**Comment by saviorisdead** [comment]
Yes, update extension as well as racer binary.

**Comment by zonyitoo** [comment]
Racer version: `1e05ca6a4fb9a07a486f7d132963fe13b8788323` (the latest commit on master branch).
Build with Rust nightly: `rustc 1.6.0-nightly (9303055f3 2015-11-19)`
RustyCode is the latest version on VSC's host.
VSC version: `Version 0.10.3 (0.10.3)`

I clicked the View Error and saw nothing in the panel:

```
Last command: 

Racer Error: 
```

I have already set the correct path of racer in settings

```son
{
    "rust.rustLangSrcPath": "/Users/zonyitoo/Projects/rust",
    "rust.racerPath": "/Users/zonyitoo/Projects/racer/target/release/racer",
    "rust.rustfmtPath": "/Users/zonyitoo/Projects/rustfmt/target/release/rustfmt",
    "rust.formatOnSave": true
}
```

**Comment by saviorisdead** [comment]
`"rust.rustLangSrcPath": "/Users/zonyitoo/Projects/rust",` should be `/Users/zonyitoo/Projects/rust/src`

**Comment by zonyitoo** [comment]
Alright, at least no error pops out. Thanks.
But it still buggy, hopefully this plugin can be improved.
