### ISSUE TITLE
Activating extension `saviorisdead.RustyCode` failed: spawn EACCES

### ISSUE THREAD

**Issue by killercup** [saviorisdead/RustyCode#83]
For some time now, I can't get this extension to work. It worked very well a few weeks ago, but something broke (either with racer, vscode, or my machine).

Looking at the developer tools, I see a bunch of  errors like this:

```plain
[Plugin Host] Activating extension `saviorisdead.RustyCode` failed: spawn EACCES.
(anonymous function) @ //Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:90
```

sometimes followed by:

```plain
Here is the error stack:  Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at SuggestService.start (/Users/pascal/.vscode-insiders/extensions/saviorisdead.RustyCode-0.11.0/out/src/services/suggestService.js:45:31)
    at activate (/Users/pascal/.vscode-insiders/extensions/saviorisdead.RustyCode-0.11.0/out/src/extension.js:15:57)
    at Function.t._callActivateOptional (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:14:10092)
    at Function.t._callActivate (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:14:9877)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:14:9749
    at Object.p [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:5:11249)
    at Object.__dirname.undefined.L.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:5:14411)
```

I'm unsure what `spawn EACCES` wants to tell me.

My settings are

```json
"rust.rustLangSrcPath": "/Users/pascal/Projekte/rust-bitrust/rust/src",
"rust.racerPath": "/Users/pascal/.multirust/toolchains/nightly/cargo/bin"
```

and vscode can definitely access both racer and the rust sources:

```sh
$ ls -lah `which racer`
-rwxr-xr-x  1 pascal  staff   4.1M Mar  7 13:35 /Users/pascal/.multirust/toolchains/nightly/cargo/bin/racer
$ ls -lah /Users/pascal/Projekte/rust-bitrust/rust/ | grep src
drwxr-xr-x  65 pascal  staff   2.2K Mar  1 10:50 src
```

I'm using OS X 10.11.3 and have tested with Visual Studio Code Version 0.10.10-insider (as well as 0.10.9). I just reinstalled racer after `multirust update`, so I have racer 1.2.6 and rustc 1.9.0-nightly (998a6720b 2016-03-07).

**Comment by KalitaAlexey** [comment]
rust.racerPath must point to *racer* executable.

**Comment by killercup** [comment]
Damn, of course I didn't try that. I'm pretty sure I moved racer (I didn't install it with `cargo install` previously) and messed this up.

The setting is kinda weirdly named, by the way. It didn't occur to me to put the trailing racer in. Maybe call it "pathToRacer" instead? But, well, it doesn't really matter. Don't make such a large breaking change just because of me.
